services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/scheduler_jobs.json:/app/backend/scheduler_jobs.json
    ports:
      - "8000:8000"
    profiles:
      - backend
